apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:5.2
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000  # Graylog UI port
        - containerPort: 12201  # GELF UDP input port
        - containerPort: 1514  # Syslog input port
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: forpasswordencryption
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: http://localhost:9000/  # External URI for Graylog UI
        - name: GRAYLOG_HTTP_BIND_ADDRESS
          value: 0.0.0.0:9000
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://opensearch:9200
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://mongodb:27017/graylog
---
apiVersion: v1
kind: Service
metadata:
  name: graylog
spec:
  selector:
    app: graylog
  ports:
  - protocol: UDP
    port: 12201
---
apiVersion: v1
kind: Service
metadata:
  name: graylog-ui
spec:
  selector:
    app: graylog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000  # Graylog UI port
---
# Optional: Service to expose Graylog REST API
apiVersion: v1
kind: Service
metadata:
  name: graylog-api
spec:
  selector:
    app: graylog
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000  # Graylog REST API port
